name: Event-based workflow execution

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  fork:
    branches:
      - main
      
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TRIGGERED the main branch workflow - event based"
      - uses: actions/checkout@v4.1.7
      - name: Use reusable  workflow
        uses: ./.github/workflows/reuseme.yml

