name: Conditional workflow execution

on:
  push:
    branches:
      - main
      - demo*

jobs:
  main_job:
    if: startsWith(github.ref 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - run: echo " Job main_job is executing on main branch push"
      - uses: action/checkout@v4.1.7
      - uses: action/setup-node@v3
        with:
          node-version: '14'
          
