name: Reusable workclow

on: 
  workflow_dispatch:

jobs:
  reusejob1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.7
      - name: Run your local action
        uses: ./  # This assumes your action is in the root of your repository
      - run: echo "My Reusable Job 1 Executed"

